# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings
remote_theme: rundocs/jekyll-rtd-theme

title: Dr C's Python Support Pages
email: William.Capehart@sdsmt.edu
description: Dr Capehart's Support Page for Python @ SD Mines


twitter_username: Bill_Capehart
github_username:  wjcapehart
sdmines_developer_homepage: https://www.sdsmt.edu/Directories/Personnel/Profile/Capehart,-William/
site.email: William.Capehart@sdsmt.edu

sass:
  sass_dir: ./_sass


# fonts
body-font: "Open Sans", BlinkMacSystemFont, "Segoe UI", Helvetica, sans-serif
head-font: "Matrix II OT", "Amiri", "Times New Roman", serif
mono-font: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace

# theme color
theme-blue: "#2980b9"
theme-red: "#e74c3c"
theme-green: "#1abc9c"
theme-orange: "#e67e22"

theme-mines-navy: "#002554"
theme-mines-gold: "#B3A369"
theme-mines-blue: "#385E9D"
theme-mines-green: "#CEDC00"
theme-mines-black: "#101820"
theme-mines-gray9: "#75787B"
theme-mines-gray4: "#BBBCBC"
theme-mines-gray1: "#D9D9D9"
theme-mines-gray0: "#EDEDED"


theme_color: "#002554"
background_color: "#002554"

plugins:
  - jekyll-feed
  - jekyll-email-protect

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
